name: Deploy ProductCatalogApi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://productcatalogapi.onrender.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}